version: '3.8'

services:
  accademiumDB:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: accademiumDB
    volumes:
      - ./pgdata:/var/lib/postgresql/accademium
    ports:
      - '5435:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - accademiumDB