export enum ApplicationDocumentType {
    LANGUAGE_CERTIFICATE = 'LANGUAGE_CERTIFICATE',
    HIGH_SCHOOL_CERTIFICATE = 'HIGH_SCHOOL_CERTIFICATE',
    MOTIVATIONAL_LETTER = 'MOTIVATIONAL_LETTER',
    CV = 'CV',
    PASSPORT_PICTURE = 'PASSPORT_PICTURE',
    ID_OR_PASSPORT = 'ID_OR_PASSPORT'
  }